### ISSUE TITLE
[Feature Request] : Serializing the imageData variable in MainActivity.kt

### ISSUE THREAD

**Issue by Elderpotato** [shubham0204/FaceRecognition_With_FaceNet_Android#11]
Model is working fine, thanks for that. But how can I switch the metric used to cosine similarity so that I can compare its performance against l2norm thanks. Btw the variable metrictobeused in frameanalyzer kt as stated in the documents does not exist.

**Comment by shubham0204** [comment]
@Elderpotato, see the [FrameAnalyser](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/blob/master/app/src/main/java/com/ml/quaterion/facenetdetection/FrameAnalyser.kt) class, see line no 57. Also, make sure you are using the [latest commit](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/commit/11c296812d4dec51f861a3ebb191dc66373f82aa).

**Comment by Elderpotato** [comment]
@shubham0204 ok will check it out, thanks for the clarification. In any case, is there a way to store the training embeddings on the device so that we dont have to process the image folder everytime we restart the application? Appreciate if you could help on this matter.

**Comment by shubham0204** [comment]
@Elderpotato I'll consider your request for the future development of the project. We can serialize the `imageData` variable ( in [MainActivity.kt](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/blob/master/app/src/main/java/com/ml/quaterion/facenetdetection/MainActivity.kt) ) and store it in the user's internal storage

**Comment by venkakat83** [comment]
I have converted the embeddings in Json Format and reading on launching the applicaition I reading them. here is the format i have used.

On Launching I am reading using Gson format.


[latest.json.zip](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/files/6140800/latest.json.zip)

**Comment by shubham0204** [comment]
@Elderpotato, we have added the feature to serialize the `imageData` variable in the latest commit. Please check it by updating your project.

**Comment by shubham0204** [comment]
This issue was closed due to inactivity.
