### ISSUE TITLE
[Error] : Getting facelist.size as 0 in FrameAnalyser.kt

### ISSUE THREAD

**Issue by gowthami77** [shubham0204/FaceRecognition_With_FaceNet_Android#16]
Hi, i am getting facelist.size is ''0'' . may i know why this is coming.
After that one i am getting this log  **I/Model: Average score for each user : {}**  
and then it is going into cache the error in cache was

**E/Model: Exception in FrameAnalyser : null**

Can you explain why this is going to cache and what i have to do to work the sample properly.

I am using using your latest code.
 once the app is launched it cannot show the bounding box over the face.

Please solve my issue as possible as fast.

**Comment by venkakat83** [comment]
Hi Gowtthami,

Make the following variable to true

private val cropWithBBoxes : Boolean = true

**Comment by gowthami77** [comment]
hi @venkakat83  i was chaged that variable to true. But there is no change in that.

**Comment by shubham0204** [comment]
@gowthami77, have you enabled the storage permission for the app?  Is the file structure ( of your images ), the same as described in the README?

**Comment by gowthami77** [comment]
@venkakat83  i created two folders in images directory in that i stored two images in each directory.

**Comment by venkakat83** [comment]
Hi Gowthami,

Can you paste the location where you have saved the files?
Ideally it should be in externalStorageDirectory. 

Note:- (From API Level 30 this storage gets deprecated)

**Comment by gowthami77** [comment]
Phone Storage/images/rahul/rahul_1.jpg

**Comment by venkakat83** [comment]
Try to store at /storage/emulated/0/images/PERSONNAME,

If you can access android device directly, 
On Android devices 
1) Go to files
2) Internal Storage
3) Create Images directory (if it doesn't exists)
4) Create PersonName directory
5) Place the .jpg images of good resolution.

**Comment by gowthami77** [comment]
i also stored in internal storage only

**Comment by venkakat83** [comment]
Try to keep the following log and check if you are saving at same location.

Log.i( "Location" , "LocationDirectory ${Environment.getExternalStorageDirectory().absolutePath}" )

If the issue still persists, then the issue will be something else.

**Comment by gowthami77** [comment]
I am getting the same path. but unable get boundaries to the face

**Comment by gowthami77** [comment]
Is there any solution? for this

**Comment by gowthami77** [comment]
i got the solution for this one added   

        android:requestLegacyExternalStorage="true"

in android manifest
