### ISSUE TITLE
l2 Norm not working as expected.

### ISSUE THREAD

**Issue by venkakat83** [shubham0204/FaceRecognition_With_FaceNet_Android#17]
Hi,

It was a great code thanks for it.

I am struggling from few days, but could able to achieve face recognition.

1) I have taken 2 photos of each my 7 friends. (of 720X720, I dont thing this matter much as we crop it to 160x160)
2) I launched and it processed it (Took some time to process it).
3) But the detection not working well. It is giving random names.

Is it possible to have SVM integrated with this module?

**Comment by shubham0204** [comment]
@venkakat83, have you tried using the cosine similarity metric? Set the `metricToBeUsed` variable to `cosine` in `FrameAnalyser.kt` to enable this.

**Comment by venkakat83** [comment]
Thanks For that, till now I was in different branch(Imgbot) and not pulled your latest master. (My bad)

I need to append my changes into master to validate again.

Just one more question :- Will this work directly or model to be trained again?

**Comment by venkakat83** [comment]
Hi, I have taken the latest branch. I have tried saving the images that are getting cropped for inference. 

model.getFaceEmbedding( cameraFrameBitmap , face.boundingBox , true )

But the faces are not getting identified at right coordinates. (looks like bounding boxes values issue) and the faces are getting inverse as well.

**Comment by venkakat83** [comment]
done following changes, it is working now. thanks

 matrix.postRotate( 90f )

made -90f to 90f

**Comment by venkakat83** [comment]
Face regonization is working, but only issue is :- If there are more faces(4 faces) in one frame, may due to processing speed it is not identifying all. (Ideally it should work).

Can we process each face analysis in separate threads?

**Comment by shubham0204** [comment]
@venkakat83, are you sure that changing -90 to 90 degrees actually works? I tried doing that and observed that the `Bitmap` got inverted by 180 degrees. We have a method in `FaceNetModel` to save a `Bitmap` to the internal storage, the `saveBitmap()` method. Please use it and check the orientation of the bitmap.

**Comment by shubham0204** [comment]
We are going to try another step before actually computing the Euclidean distance ( L2 norm of `x2 - x1`  ). We can normalize both the vectors `x1` and `x2` before computing the Euclidean distance. I'll implement it and test it as well.

**Comment by venkakat83** [comment]
> @venkakat83, are you sure that changing -90 to 90 degrees actually works? I tried doing that and observed that the `Bitmap` got inverted by 180 degrees. We have a method in `FaceNetModel` to save a `Bitmap` to the internal storage, the `saveBitmap()` method. Please use it and check the orientation of the bitmap.

Yes, I did the same, with +90 the image cropped well without 180 degree orientation.

**Comment by venkakat83** [comment]
> We are going to try another step before actually computing the Euclidean distance ( L2 norm of `x2 - x1` ). We can normalize both the vectors `x1` and `x2` before computing the Euclidean distance. I'll implement it and test it as well.

In my case cosine is giving good results than l2.

**Comment by shubham0204** [comment]
@venkakat83, I have made a [new commit](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/commit/bcf4ee4001533ca2aa4d59bd822c2f17d46aa291) to the project in order to add the above-mentioned vector normalization. All embeddings ( vectors ) from the FaceNet model will be normalized first and then the Euclidean distance between those normalized vectors will be calculated.

**Comment by shubham0204** [comment]
I am closing this issue because of no active participants. If this issue reoccurs, you may reopen this issue.

**Comment by venkakat83** [comment]
Thanks Shubham for your support. I have quick question, if we run the same on Edge devices with AI processor, how can I validate the load of GPU or AI Processor.

If you have any info kindly share.

**Comment by shubham0204** [comment]
We can run our TFLite models on Mobile GPUs, but a limited no. of ops are supported. See [GpuDelegate](https://www.tensorflow.org/lite/performance/gpu).
