### ISSUE TITLE
App is hanging with 300 Images

### ISSUE THREAD

**Issue by rameshkec85** [shubham0204/FaceRecognition_With_FaceNet_Android#30]
I really appreciated this works very well with few images. How to avoid blocking UI and also to work smoothly with many no of images ?

**Comment by shubham0204** [comment]
@rameshkec85 I have resolved the issue in the [latest commit](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/commit/57c806868005aa1de4d9be2e1d8e9f3aa6c1b4dd). Please verify if it resolves the issue.

**Comment by rameshkec85** [comment]
Its worked. Thanks
