### ISSUE TITLE
Can the source of the photo not be from storage but from a photo link?

### ISSUE THREAD

**Issue by abdullahJufri** [shubham0204/FaceRecognition_With_FaceNet_Android#36]
Hi,
Can the source of the photo not be from storage but from a photo url?
thanks

**Comment by shubham0204** [comment]
@abdullahJufri The app currently only reads image from the device's local storage. You can modify the `MainActivity.kt` file and use the method `fileReader.run( images , fileReaderCallback )` where `images` is an `ArrayList<Pair<String,Bitmap>>`. You can populate `images` by downloading them from a URL and pass it to `fileReader.run` to get the embeddings generated.

**Comment by abdullahJufri** [comment]
Thanks @shubham0204
