### ISSUE TITLE
 Migrating to ML Kit

### ISSUE THREAD

**Issue by SushantGautam** [shubham0204/FaceRecognition_With_FaceNet_Android#4]
I think we can migrate to Ml Kit now for this demo.
https://developers.google.com/ml-kit/migration

**Comment by shubham0204** [comment]
@SushantGautam Can you please elaborate your problem?

**Comment by SushantGautam** [comment]
I came across your repo and just was curious to know if you would like to migrate to ML Kit in the future as Google is now separating its solutions for on-device machine learning from Firebase ML Kit to ML Kit. 
I am now having any problems or issues with your code.  

You have done a really great job and contributed to the community. :)

**Comment by shubham0204** [comment]
@SushantGautam, thanks for highlighting the change. All Firebase MLKit libraries have been replaced by Google MLKit libraries. See this [commit](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/commit/394789101947bf79eb754055d2852e75d54e6817).
