### ISSUE TITLE
[Feature Request] : Face detection in landscape orientation 

### ISSUE THREAD

**Issue by SushantGautam** [shubham0204/FaceRecognition_With_FaceNet_Android#6]
Can we adapt codes to support Landscape  mode?

**Comment by shubham0204** [comment]
@SushantGautam , the app can now work in the landscape mode. Please check it by updating your project.

**Comment by SushantGautam** [comment]
> @SushantGautam , the app can now work in the landscape mode. Please check it by updating your project.

Cool

**Comment by shubham0204** [comment]
This issue was closed due to inactivity.
